package entity

import "time"

type Request struct {
	RootID                      string     `json:"root_id"`
	VersionID                   *string    `json:"version_id"`
	RequestNumber               *string    `json:"request_number"`
	MosRuRequestNumber          *string    `json:"mos_ru_request_number"`
	DateOfCreation              time.Time  `json:"date_of_creation"`
	DateOfStart                 time.Time  `json:"date_of_start"`
	NameOfSource                *string    `json:"name_of_source"`
	NameOsSourceENG             *string    `json:"name_of_source_eng"`
	NameOfCreator               *string    `json:"name_of_creator"`
	IncidentFeature             *string    `json:"incident_feature"`
	RootIdentifcatorOfMaternal  *string    `json:"root_identificator_of_maternal"`
	NumberOfMaternal            *string    `json:"number_of_maternal"`
	LastNameRedacted            *string    `json:"last_name_redacted"`
	RoleOfUser                  *string    `json:"role_of_user"`
	Commentaries                *string    `json:"commentaries"`
	DeffectCategoryName         *string    `json:"deffect_category_name"`
	DeffectCategoryID           *string    `json:"deffect_category_id"`
	DeffectCategoryNameENG      *string    `json:"deffect_category_name_eng"`
	DeffectName                 *string    `json:"deffect_name"`
	ShortDeffectName            *string    `json:"short_deffect_name"`
	DeffectID                   *string    `json:"deffect_id"`
	CodeOfDeffect               *string    `json:"code_of_deffect"`
	NeedForRevision             *string    `json:"need_for_revision"`
	Description                 *string    `json:"description"`
	PresenceOfQuestion          *string    `json:"presence_of_question"`
	UrgencyCategory             *string    `json:"urgency_category"`
	UrgencyCategoryENG          *string    `json:"urgency_category_eng"`
	District                    *string    `json:"district"`
	DistrictCode                *string    `json:"district_code"`
	Hood                        *string    `json:"hood"`
	HoodCode                    *string    `json:"hood_code"`
	AddressOfProblem            *string    `json:"adress_of_problem"`
	AddressUNOM                 int        `json:"adress_unom"`
	Porch                       *string    `json:"porch"`
	Floor                       *string    `json:"floor"`
	FlatNumber                  *string    `json:"flat_number"`
	DispetchersNumber           *string    `json:"dispetchers_number"`
	OwnerCompany                *string    `json:"owner_company"`
	ServingCompany              *string    `json:"serving_company"`
	PerformingCompany           *string    `json:"performing_company"`
	InnOfPerformingCompany      *string    `json:"inn_of_performing_company"`
	RequestStatus               *string    `json:"request_status"`
	RequestStatusENG            *string    `json:"request_status_eng"`
	ReasonForDecline            *string    `json:"reason_for_decline"`
	ReasonForDeclineID          *string    `json:"id_of_reason_for_decline"`
	ReasonForDeclineOfOrg       *string    `json:"reason_for_decline_of_org"`
	ReasonForDeclineOfOrgID     *string    `json:"id_of_reason_for_decline_of_org"`
	WorkTypeDone                *string    `json:"work_type_done"`
	IDWorkTypeDone              *string    `json:"id_work_type_done"`
	UsedMaterial                *string    `json:"used_material"`
	GuardingEvents              *string    `json:"guarding_events"`
	GuardingEventsID            *string    `json:"id_guarding_events"`
	Effeciency                  *string    `json:"efficiency"`
	EffeciencyENG               *string    `json:"efficiency_eng"`
	TimesReturnes               *int       `json:"times_returned"`
	DateOfLastReturnForRevision *time.Time `json:"date_of_last_return_for_revision"`
	BeingOnRevision             *string    `json:"being_on_revision"`
	AlertedFeature              *string    `json:"alerted_feature"`
	ClosureDate                 *time.Time `json:"closure_date"`
	WantedTimeFrom              *time.Time `json:"wanted_time_from"`
	WatnedTimeTo                *time.Time `json:"wanted_time_to"`
	DateOfReview                *time.Time `json:"date_of_review"`
	Review                      *string    `json:"review"`
	GradeForService             *string    `json:"grade_for_service"`
	GradeForServiceENG          *string    `json:"grade_for_service_eng"`
	PaymentCategory             *string    `json:"payment_category"`
	PaymentCategoryENG          *string    `json:"payment_category_eng"`
	PayedByCard                 *string    `json:"payed_by_card"`
	DateOfPreviousRequestClose  *time.Time `json:"date_of_previous_request_close"`
}
